apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.13.1
    releaseName: gha-runner-scale-set-kubernetes
    valuesFile: values.yaml
