"""
FILE_NAME: generate_properties.py
DESCRIPTION: Write sonar-project.properties from PR, app name, and ng-ui extras.
VERSION: 1.0.0
AUTHORS: DevOps Team
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

PROJECT_KEY_RE = re.compile(r"^[A-Za-z0-9_.:-]+$")
APP_BUILD_TYPES = ("", "maven", "ng-ui", "dotnet")
LCOV_REL = Path("coverage") / "lcov.info"
LOCKFILE_NAME = "package-lock.json"
DC_HTML = "reports/dependency-check-report.html"
DC_JSON = "reports/dependency-check-report.json"


def build_properties(
    project_key: str,
    application_name: str,
    app_build_type: str,
    pr_key: str,
    pr_branch: str,
    pr_base: str,
    base_dir: Path,
) -> list[tuple[str, str]]:
    """INTENT: Assemble sonar-project.properties rows.
    INPUT: scan identity, optional PR refs, workspace base
    OUTPUT: ordered key/value pairs
    ROLE: helper
    SIDE_EFFECTS: reads coverage/lcov.info existence
    """
    rows: list[tuple[str, str]] = [
        ("sonar.projectKey", project_key),
        ("sonar.projectName", application_name),
    ]
    if app_build_type == "ng-ui":
        rows.append(("sonar.sources", f"apps,{LOCKFILE_NAME}"))
        rows.append(("sonar.inclusions", f"apps/**,{LOCKFILE_NAME}"))
        rows.append(("sonar.dependencyCheck.htmlReportPath", DC_HTML))
        rows.append(("sonar.dependencyCheck.jsonReportPath", DC_JSON))
        if (base_dir / LCOV_REL).is_file():
            rows.append(("sonar.javascript.lcov.reportPaths", LCOV_REL.as_posix()))
    pr_values = (pr_key, pr_branch, pr_base)
    if any(pr_values):
        if not all(pr_values):
            raise ValueError("pr_key, pr_branch, and pr_base must be set together")
        rows.append(("sonar.pullrequest.key", pr_key))
        rows.append(("sonar.pullrequest.branch", pr_branch))
        rows.append(("sonar.pullrequest.base", pr_base))
    return rows


def render(rows: list[tuple[str, str]]) -> str:
    """INTENT: Format properties file text.
    INPUT: key/value rows
    OUTPUT: file body with trailing newline
    ROLE: helper
    SIDE_EFFECTS: none
    """
    lines = [
        "# Generated by actions/security/sonar-scan",
        *[f"{key}={value}" for key, value in rows],
        "",
    ]
    return "\n".join(lines)


def write_outputs(path: str, outputs: dict[str, str]) -> None:
    """INTENT: Append action outputs when --output is set.
    INPUT: file path, key/value map
    OUTPUT: none
    ROLE: helper
    SIDE_EFFECTS: appends to output file
    """
    with open(path, "a", encoding="utf-8") as fh:
        for key, value in outputs.items():
            if "\n" in value:
                fh.write(f"{key}<<EOF\n{value}\nEOF\n")
            else:
                fh.write(f"{key}={value}\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate sonar-project.properties")
    parser.add_argument("--project-key", default="")
    parser.add_argument("--application-name", default="")
    parser.add_argument("--app-build-type", default="")
    parser.add_argument("--pr-key", default="")
    parser.add_argument("--pr-branch", default="")
    parser.add_argument("--pr-base", default="")
    parser.add_argument("--project-base-dir", default=".")
    parser.add_argument("--properties-path", default="")
    parser.add_argument("--output", default="")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print properties without writing a file",
    )
    args = parser.parse_args()

    project_key = args.project_key.strip()
    application_name = args.application_name.strip() or project_key
    app_build_type = args.app_build_type.strip()
    pr_key = args.pr_key.strip()
    pr_branch = args.pr_branch.strip()
    pr_base = args.pr_base.strip()
    base_dir = Path(args.project_base_dir.strip() or ".").resolve()

    if not project_key or not PROJECT_KEY_RE.match(project_key):
        print("ERROR: --project-key must match [A-Za-z0-9_.:-]+", file=sys.stderr)
        return 1
    if not application_name:
        print("ERROR: --application-name is required", file=sys.stderr)
        return 1
    if "\n" in application_name or "\r" in application_name:
        print("ERROR: --application-name must be a single line", file=sys.stderr)
        return 1
    if app_build_type not in APP_BUILD_TYPES:
        print("ERROR: --app-build-type must be maven, ng-ui, dotnet, or empty", file=sys.stderr)
        return 1

    try:
        rows = build_properties(
            project_key,
            application_name,
            app_build_type,
            pr_key,
            pr_branch,
            pr_base,
            base_dir,
        )
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    body = render(rows)
    dest = args.properties_path.strip()
    if not dest:
        dest = str(base_dir / "sonar-project.properties")
    if not args.dry_run:
        Path(dest).write_text(body, encoding="utf-8")
        print(f"wrote {dest}")
    print(body, end="")

    outputs = {
        "properties_path": dest,
        "properties": body.rstrip("\n"),
        "app_build_type": app_build_type,
    }
    if args.output.strip():
        write_outputs(args.output.strip(), outputs)
    return 0


if __name__ == "__main__":
    sys.exit(main())
