apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:scc:github-arc
  labels:
    app.kubernetes.io/part-of: github-arc
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - github-arc
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-arc-scc
  labels:
    app.kubernetes.io/part-of: github-arc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:github-arc
subjects:
  - kind: ServiceAccount
    name: gha-runner-scale-set-controller-gha-rs-controller
  - kind: ServiceAccount
    name: gha-runner-scale-set-gha-rs-no-permission
  - kind: ServiceAccount
    name: gha-runner-scale-set-kubernetes-gha-rs-kube-mode
  - kind: ServiceAccount
    name: gha-runner-scale-set-k8s-novolume-gha-rs-kube-mode
  - kind: ServiceAccount
    name: gha-runner-scale-set-k8s-novolume-gha-rs-no-permission
